### ISSUE TITLE
Unable to replace certain text - General_

### ISSUE THREAD

**Issue by crbon** [Findus23/plugin-CustomiseTranslations#1]
Hi there.

I am fairly new to Matomo and have recently started using your plugin to customise some of the Matomo strings/titles. It works great for the most part, but I have noticed that I am unable to change certain strings.

I ran into an issue when trying to rename **General_ColumnPageviews**. It gives me an error `: The plugin 'General' doesn't exist.`. I have found/searched up the `Translation Key` using  `Translation Search`.

Is this a restriction of Matomo, a limitation of the plugin or simply an issue on my instance of Matomo?

Any help would be appreciated :)

**Comment by Findus23** [comment]
Hi,

I'm sorry that this issue got lost (I guess I didn't see the E-Mail at the time).

This is indeed an arbitrary limitation of the plugin. I check the first part of the name against the list of plugins forgetting that there are a few like `General` without a corresponding plugin.

This is fixed in the 0.2.0 plugin release.
